apiVersion: integration/v1
kind: Trigger
name: alertmanager-trigger-alert-fired
version: 1
summary: Alertmanager alert fired

description: |
  This trigger takes in the contents of an Alertmanager alert and presents it as an output event.

responders:
- webhook

schemas:
  event:
    source: file
    file: event.schema.json

build:
  apiVersion: build/v1
  kind: Docker

publish:
  repository: relaysh/alertmanager-trigger-alert-fired

examples:
- summary: When a Prometheus Alertmanager alert fires
  content:
    apiVersion: v1
    kind: Trigger
    name: alertmanager-alert
    source:
      type: webhook
      image: relaysh/alertmanager-trigger-alert-fired
    binding:
      parameters:
        event_payload: !Data event_payload